version: '3'

services:
  frontend:
    build: ./frontend-side
    restart: unless-stopped
    command: npm run start
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - HOST=http://realworld-docker.com
      - MONGODB_URI=mongodb://backend:27017/realworld_db
    depends_on:
      - backend

  backend:
    image: mongo:latest
